const para1="Problemele sociale și culturale au fost din ce în ce mai recunoscute că joacă un rol fundamental în determinarea faptului dacă lucrătorii vor fi dispuși să participe activ la inițiativele de gestionare a cunoștințelor. În mod inevitabil, acest lucru a determinat organizațiile să utilizeze diferite tipuri de practici manageriale pentru a încuraja angajații să participe la activități și inițiative de gestionare a cunoștințelor. Accentul acestui capitol este asupra modului în care diferitele practici de management a resurselor umane (HRM) pot avea un impact asupra atitudinii angajaților față de activitățile de gestionare a cunoștințelor și asupra participării la acestea.";
const para2="Utilizarea practicilor HRM poate fi văzută încercarea de a crea o atitudine pozitivă a angajaților față de participarea la activități de management a cunoștințelor organizaționale, ci și de a-i antrena pe angajați să fie mai loiali angajatorilor lor. Acest lucru se datorează faptului că, în cazul în care lucrătorii nu sunt fideli organizației de care fac parte, există riscul ca aceste organizații să piardă orice acces la cunoștințele lucrătorilor din cauza prin fluctuația de personal (Eckardt și colab. 2014). Problema pierderii de cunoștințe prin fluctuația personalului este o problemă obișnuită cu care se confruntă firmele care necesită cunoștințe specifice. Astfel, practicile HRM legate de sprijinirea eforturilor organizaționale de gestionare a cunoștințelor ar trebui să fie preocupate atât de dezvoltarea angajamentului și a loialității lucrătorilor, cât și de a convinge lucrătorii să împartă sau să creeze cunoștințe.";
const paragraph1 = {
    title:"Capitolul I- Introducere",
    paragraphs:[para1 , para2],
    test:false,
}


const para21 ="Această secțiune ia în considerare două motive separate pentru care practicile HRM pot contribui la apariția comportamentelor și atitudinilor necesare pentru ca inițiativele de management a cunoștințelor să aibă succes. În primul rând, practicile HRM pot fi utilizate pentru a motiva lucrătorii să participe la activități de gestionare a cunoștințelor prin influențarea tipului de factori socio-culturali care au fost descoperiți să fie cruciali pentru participarea angajaților la activitățile de management a cunoștințelor. Al doilea mod în care practicile HRM pot fi utilizate pentru a susține și facilita activitățile de management al cunoștințelor organizaționale este prin dezvoltarea angajamentului organizațional al angajaților, sugerându-se că angajamentul poate fi o variabilă importantă care mediază relația dintre practicile HRM și activitățile de management al cunoștințelor.";
const para22 ="Disponibilitatea angajaților de a participa la activitățile de gestionare a cunoștințelor organizaționale depinde de percepția angajaților asupra posibilelor efecte pozitive și negative ale acestui lucru. Dacă beneficiile posibile sunt mai mari decât dezavantajele, atunci participarea la activități de management al cunoștințelor va fi mai probabilă. Dacă simt opusul, că consecințele negative le pot depăși pe cele pozitive, sunt mai predispuși să-și „păstreze” cunoștințele și să nu participe la activitățile de gestionare a cunoștințelor. Factorii care determină dacă un angajat își împărtășește cunoștințele sau le păstrează, includ măsura în care aceștia percep dacă interesele lor sunt în conflict cu a angajatorii lor, nivelul de  identificare cu  grupul și a comunității și în ce măsură au încredere în colegii lor. Politicile HRM au potențialul de a juca un rol crucial care influențează modul în care angajații rezolvă astfel de decizii de împărtăși sau a păstra cunoștințe prin motivarea acestora de a participarea la activitățile de gestionare a cunoștințelor. De exemplu, dezvoltarea unor bune relații sociale bazate pe încredere sau dezvoltarea unui puternic sentiment de identitate a echipei ar putea fi realizat prin furnizarea de traininguri care să aducă angajații împreună pentru a învăța colectiv sau prin proiectarea de locuri de muncă care necesită colaborare interpersonală";
const para23 ="Vorbind despre motivație, este necesar să se facă distincția între motivația intrinsecă și extrinsecă. Motivația intrinsecă se referă la plăcerile și sentimentele pozitive pe care oamenii le pot obține din simpla desfășurare a unei sarcini sau activități. Astfel, dacă un inginer software obține plăcerea din procesul de scriere a codului computerului care este eficient, ei sunt motivați intrinsec să desfășoare această activitate. În contrast, motivația extrinsecă se referă la recompensele externe pe care le obțin oamenii din îndeplinirea unei sarcini, cum ar fi banii. Astfel, un inginer software este extrinsec motivat să scrie codul computerului dacă principalul motiv pentru care o face este pentru salariul pe care îl primește. Astfel, practicile HRM pot fi utilizate pentru a proiecta locuri de muncă care sunt intrinsec interesante și provocatoare și care încurajează și îi motivează pe angajați să își folosească și să împărtășească cunoștințele lor. În schimb, practica HRM, cum ar fi sistemele de recompensă, pot fi utilizată pentru a motiva în mod extrinsec lucrătorii să participe la activități de gestionare a cunoștințelor, oferind stimulente financiare pentru aceasta.";
const para24 ="A doua modalitate de a înțelege de ce practicile HRM pot influența pozitiv atitudinile și comportamentele legate de cunoștințele lucrătorului este prin conectarea la conceptul de angajament organizațional. Sentimentul de identitate a oamenilor ca parte a unui grup, echipă sau organizație poate influența în mod semnificativ dorința lor de a participa la activitățile de management a cunoștințelor. În termeni generali, cu atât este mai mare sentimentul de identitate a unei persoane cu o echipă sau grup,  cu atât sunt mai susceptibile de a participa la activități de gestionare a cunoștințelor care implică alți membri ai grupului / echipei sau care sunt percepute ca fiind în beneficiul grupului. Astfel, cu cât angajații se identifică mai mult cu organizația pentru care lucrează, cu atât vor avea mai multe șanse să participe la activități de management al cunoștințelor organizaționale. În acest context, rolul practicilor HRM este, prin urmare, de a ajuta la dezvoltarea nivelurilor angajamentului organizațional al angajaților.";
const para25 ="Angajamentul organizațional= Sentimentul de atașament emoțional pe care îl simt oamenii față de organizațiile pentru care lucrează, care se poate reflecta în alinierea valorilor și obiectivelor individuale și organizaționale.";
const para26 ="Un număr de scriitori sugerează că nivelul de angajament pe care îl simt angajații pentru organizațiile în care lucrează poate afecta atât atitudinile și comportamentele lor de partajare a cunoștințelor, cât și nivelul de loialitate (Byrne 2001, Storey și Quintas 2001, Hislop 2002a; O'Neill și Adya 2007, vezi Ilustrația 15.11). Au existat, de asemenea, o serie de studii empirice care au furnizat dovezi în sprijinul acestor argumente. Astfel, Robertson și O'Malley Hammersley (2000) au constatat că nivelurile de angajament organizațional au afectat memoria și atitudinea angajaților față de procesele de cunoaștere. În al doilea rând, Han și colab. (2010), într-un studiu care a implicat personal care lucrează în opt companii taiwaneze de înaltă tehnologie, a constatat că acest lucru este cazul participării angajaților la procesele de luare a deciziilor organizaționale. Astfel, au descoperit că nivelurile de participare la procesele de luare a deciziilor au fost pozitiv legate de sentimentul de  „stăpânire” psihologică pe care lucrătorii îl simțeau asupra unor astfel de decizii, nivelurile de „stăpânire” psihologică fiind legate pozitiv de nivelurile angajaților atât de angajamentul organizațional, cât și de partajarea cunoștințelor. Camelo-Ordaz și colab. (2017) au constatat că o serie de practici HRM cu implicare ridicată (include practici de recrutare și selecție destinate selectării persoanelor pe baza potrivirii lor cu organizația, sisteme de recompensă și evaluare a reclamei bazate pe echipe, sisteme de recompensă care au încurajat schimbul de cunoștințe și furnizarea de oportunități extinse de formare și dezvoltare) a influențat nivelurile de schimb de cunoștințe ale angajaților în mod indirect, afectându-le nivelurile de angajament organizațional.";
const para27 = "Practici de muncă cu implicare ridicată, schimb de cunoștințe și performanță a serviciilor.";
const para28 = "Flinchbaugh și colab. (2016) au examinat impactul practicilor de lucru cu implicare ridicată în cadrul echipelor asupra nivelurilor de schimb de cunoștințe și a performanței echipei. Au studiat echipele în cadrul organizațiilor non-profit responsabile de acordarea de îngrijiri rezidențiale și sprijin tinerilor cu probleme semnificative de sănătate mentală.. În acest context, munca în echipă și comunicarea au fost o componentă importantă în asigurarea unei îngrijiri eficiente. Practicile de lucru cu implicare ridicată au inclus furnizarea feedback-ului cu privire la performanța muncii, implicarea în procesele cheie de luare a deciziilor de muncă și furnizarea de informații cu privire la performanța financiară a organizației. Analiza rezultatelor sondajului lor a constatat că utilizarea practicilor de muncă cu implicare ridicată a fost pozitiv legată de nivelul de schimb de cunoștințe bazat pe echipă și, de asemenea, că nivelurile de schimb de cunoștințe bazate pe echipă au fost pozitiv legate de nivelurile de performanță ale serviciilor echipei. Au descoperit, de asemenea, că nivelurile de perspectivă, luând măsura în care oamenii sunt sensibili și conștienți de perspectiva celorlalți, au moderat relația dintre practicile de muncă cu implicare ridicată și nivelurile de schimb de cunoștințe În termeni practici, Flinchbaugh et al (2016) au concluzionat că utilizarea practicilor de muncă cu implicare ridicată reprezintă o modalitate potențial utilă de a spori nivelurile de schimb de cunoștințe și performanța echipei. În raport cu importanța luării perspectivei, au constatat, de asemenea, că conștientizarea angajaților cu privire la practicile de muncă cu implicare ridicată a fost variabilă, sugerând că, comunicarea conducerii cu privire la astfel de activități este importantă pentru a asigura conștientizarea efectivă a angajaților.";

const paragraph2 ={
    title:"De ce practicile HRM sunt importante pentru managementul cunoștințelor?",
    paragraphs:[para21 ,para22 , para23 , para24, para25, para26, para27, para28],
    test:false,
}

const titlu3 = "Capitolul 3- Practici HRM și managementul cunoștințelor";
const para31 = "Această secțiune examinează modul în care unele practici specifice HRM pot fi utilizate pentru a modela atitudinile și comportamentele față de activitățile de management al cunoștințelor organizaționale, cu o serie de exemple relevante folosite pentru a ilustra și susține punctele formulate.";
const para32 = "1. Recrutare și selecție";
const para33 = "Literatura de management a cunoștințelor sugerează o serie de moduri în care procesele de recrutare și selecție pot fi utilizate pentru a sprijini activitățile de gestionare a cunoștințelor. În primul rând, pot fi folosite pentru a recruta oameni ale căror valori sunt compatibile cu cele ale culturii organizaționale existente. În al doilea rând, pot fi folosite pentru a selecta persoane cu trăsături de personalitate care sunt favorabile schimbului de cunoștințe.";
const para34 = "În legătură cu primul subiect, atât Swart și Kinnie (2003), cât și Robertson și Swan (2003) sugerează că recrutarea persoanelor ale căror valori sunt aliniate cu cele ale companiei a fost un factor important în succesul companiilor pe care le-au examinat. Ambele lucrări au prezentat analiza unei singure firme de succes care utilizează cunoștințe, care a avut succes nu numai în termeni economici și economici restrânși, ci și în ceea ce privește personalul fericit și angajat în muncă, ceea ce a însemnat că niciuna dintre organizații nu a avut probleme semnificative de fluctuație a personalului. Modul în care astfel de forme de recrutare întăresc și susțin activitățile de cunoaștere organizațională indică faptul că prin recrutarea de personal, ale căror valori și norme sunt compatibile cu cele care există într-o organizație, noii angajați ar putea dezvolta un puternic sentiment de identitate cu angajatorul și colegii de muncă. Un alt studiu empiric care a examinat acest subiect și care a găsit o legătură pozitivă între recrutarea bazată pe potrivire și atitudinile față de schimbul de cunoștințe a fost realizat de Chen și colab. (2011).";
const para35 = "Chen și colab. (2011) au investigat modul în care o serie de practici diferite de MRU au afectat disponibilitatea oamenilor din cadrul echipelor de cercetare și dezvoltare (R&D) din Taiwan de a împărtăși cunoștințe. Toate echipele de cercetare și dezvoltare chestionate au fost în industrii de înaltă tehnologie (electronică, comunicații, semiconductori de mașini de precizie și optoelectronică). Au analizat sondajele a peste 200 de angajați din cincizeci de echipe separate RAD. În general, au descoperit că majoritatea practicilor de HRM examinate au afectat comportamentele de schimb de cunoștințe ale echipelor. În primul rând, au descoperit că recrutarea persoanelor care se potriveau cu cultura și valorile existente au promovat schimbul de cunoștințe. În al doilea rând, au descoperit că disponibilitatea oamenilor de a împărtăși cunoștințe era, de asemenea, relaționată pozitiv cu măsura în care percepeau că angajatorul acorda atenție dezvoltării carierei lor pe termen lung. În cele din urmă, au descoperit că evaluările de performanță, care au fost concentrate pe o persoană, au inhibat dorința oamenilor de a împărtăși cunoștințele în cadrul echipelor. Astfel, în tipul de echipe pe care le-au examinat, evaluările de performanță axate pe echipă, mai degrabă decât individual, sunt mai susceptibile să faciliteze. O ipoteză finală care a fost testată, dar care nu a fost susținută de studiu a fost folosirea unui sistem de premii pentru a crește dorința persoanelor de a participa în schimbul de cunoștințe. Astfel, acest studiu subminează argumentul potrivit căruia recompensele financiare pot fi folosite pentru a motiva oamenii să împărtășească cunoștințe.";
const para36 = "Întrebare: Acest caz sugerează că, în contextele de lucru bazate pe echipă, recompensele și sistemele de evaluare axate pe individ pot inhiba disponibilitatea oamenilor de a împărtăși cunoștințe. Puteți identifica locuri de muncă în care munca nu este bazată pe echipă și colaborare, și unde recompensele și sistemele de evaluare axate individual pot motiva oamenii să împărtășească cunoștințele?";
const para37 = "Dacă se acceptă premisa acestor studii (că trăsăturile de personalitate pot influența atitudinile generale ale oamenilor față de schimbul de cunoștințe, ceea ce face ca anumite tipuri de persoane să fie în general mai deschise să facă acest lucru decât altele), atunci încercarea de a recruta persoane cu trăsături de personalitate adecvate poate reprezenta un alt mod prin care recrutarea și procesele de selecție pot fi utilizate pentru a susține activitățile de cunoaștere organizațională. Cu toate acestea, lipsa cercetărilor pe această temă și constatările contradictorii ale studiilor care au fost făcute înseamnă că, în acest moment, utilizarea testelor de personalitate pentru a identifica atitudini pozitive de schimb de cunoștințe este ceva ce trebuie făcut cu prudență.";
const para38 = "Problema finală de recrutare și selecție abordată se referă la contextul multinaționalelor în care, inevitabil, angajații cărora li se cere să comunice și să împărtășească cunoștințe au diferite limbi materne și au competențe de comunicare în limbi non-native de niveluri diferite. Importanța limbajului pentru schimbul de cunoștințe în acest context a fost luată în considerare anterior în capitolul 13 privind colaborarea între comunități. Peltokorpi și Vaara (2014) au examinat impactul recrutării sensibile la limbă asupra proceselor de transfer de cunoștințe în multinaționale. Sensibilitățile lingvistice se referă atât la competența lingvistică a personalului de la sediul societății-mamă în limba filialelor, cât și la competența lingvistică a limbii de bază utilizate la sediul central a personalului din filialele. Peltokorpi și Vaara (2014) au constatat că recrutarea sensibilă la limbă în multinaționale a fost relaționată pozitiv cu nivelurile de transfer de cunoștințe. Acest lucru nu se datorează doar faptului că a facilitat comunicarea interpersonală eficientă, ci și că a făcut mai ușor pentru oameni să dezvolte rețele internaționale diverse și să aibă un sentiment mai puternic de identitate comună cu alți angajați din cadrul organizației, care nu au aceeași limbă maternă. Astfel, în acest context, recrutarea pentru competențe generale și lingvistice este un mecanism potențial important pentru a facilita transferul și colaborarea intra organizațională a cunoștințelor.";
const para39 = "2. Job design";
const para311 = "În domeniul proiectării locurilor de muncă există un consens puternic cu privire la cea mai bună modalitate de structurare a posturilor pentru a facilita atitudini adecvate de schimb de cunoștințe. În termeni generali, munca ar trebui să aibă trei caracteristici cheie: ar trebui să fie interesantă și captivantă, în al doilea rând, angajații ar trebui să aibă un nivel ridicat de autonomie în ceea ce privește luarea deciziilor și rezolvarea problemelor și, în cele din urmă, ar trebui să încurajeze și să necesite o colaborare interpersonală. De exemplu, studiul Chen și colab. (2011) privind legătura dintre conflict și schimbul de cunoștințe efectuat în companiile chineze de software a recomandat ca schimbul de cunoștințe interpersonal ar fi încurajat dacă angajații ar avea sarcini de muncă solicitante și semnificative, împreună cu niveluri ridicate de autonomie. În ceea ce privește prima caracteristică, nu numai că sarcinile ar trebui să fie antrenante și satisfăcătoare, oferind angajaților oportunități de a-și utiliza în mod eficient abilitățile și cunoștințele existente, dar ar trebui să le ofere și oportunități de a-și dezvolta continuu cunoștințele și abilitățile (Robertson și O'Malley Hammersley, 2000; Swart și Kinnie, 2003). De exemplu, Monks și colab. (2016) au găsit o relație pozitivă între oportunitățile de îmbunătățire a învățării și disponibilitatea oamenilor de a se angaja în procese de schimb de cunoștințe. Importanța pentru cei ce lucrează cu cunoștințe de a avea o sarcini interesante și solicitante este susținută de concluziile studiului Horowitz și colab. (2003) aplicat unui grup de persoane care lucrează cu cunoștințe, din Singapore, care a constatat că furnizarea unei munci antrenante a fost clasificată de către manageri ca cel mai important factor ce ajută la păstrarea persoanelor care lucrează cu cunoștințe. În mod similar, Han și colab. (2010), așa cum s-a subliniat anterior, a constatat că implicarea în luarea deciziilor a fost legată pozitiv de nivelurile de angajament organizațional și de schimb de cunoștințe.";
const para312 = "3.Training";
const para313 = "În timp ce, aşa cum am subliniat, oferirea de oportunităţi pentru autodezvoltare poate fi integrată în modul în care sunt organizate activităţile de lucru ale oamenilor, aceasta poate fi realizată şi prin oferirea oportunităţilor adecvate de a întreprinde o instruire formală. Prin urmare, cercetările sugerează că lucrătorii cu cunoştinţe consideră că furnizarea de astfel de oportunităţi de către angajatorii lor este extrem de importantă (Robertson & O’Malley Hammersley, 2000; Hunter et al., 2002). De exemplu, Yalabik et al. (2017) sugerează că oferirea unei formări adecvate lucrătorilor din domeniul cunoştinţelor poate fi o modalitate cheie de a contribui la dezvoltarea angajamentului şi loialităţii lor. În timp ce furnizarea unor astfel de oportunităţi este potenţial o sabie cu două tăişuri pentru angajatori (deoarece sprijinirea acestor activităţi poate facilita plecarea personalului), fără a sprijini dezvoltarea continuă, este posibil ca personalul să plece oricum. Garvey & Williamson (2002) sugerează că cel mai util tip de instruire pentru a sprijini o cultură a învăţării şi a dezvoltării cunoştinţelor nu este să investeşti în formare de abilităţi „înguste”, ci formarea cu un scop mai larg pentru a încuraja reflexivitatea, învăţarea prin experimentare şi cum să conducem dialoguri critice cu ceilalţi. Acest lucru este întărit de studiul empiric al lui Monks et al. (2016), care au descoperit că oferirea de oportunităţi de îmbunătăţire a învăţării, cum ar fi instruirea, a fost relaţionată pozitiv atât cu reflexivitatea, cât şi cu disponibilitatea de a se angaja în procesele de împărtăşire de cunoştinţe. Hansen et al. (1999) sugerează că tipul de instruire oferit ar trebui să reflecte abordarea particulară a managementului cunoştinţelor pe care o organizaţie o adoptă. De exemplu, în ceea ce priveşte distincţia lor între abordări bazate pe codificare şi cele bazate pe personalizare pentru gestionarea cunoştinţelor, ei susţin că furnizarea de formare bazată pe IT este relevantă pentru organizaţiile care urmăresc o strategie bazată pe codificare, în timp ce instruirea pentru dezvoltarea abilităţilor interpersonale şi a muncii în echipă este cea mai potrivită pentru organizaţiile care urmăresc o strategie de gestionare a cunoştinţelor bazată pe personalizare.";
const para314 = "Întărind această idee despre relaţionarea tipului de instruire oferit de abordarea adoptată a managementului cunoştinţelor, o serie de studii privind rolul tehnologiilor Web 2.0 pentru a facilita gestionarea cunoştinţelor sugerează că furnizarea de instruire privind utilizarea face ca aceste tehnologii să încurajeze lucrătorii să le utilizeze pentru împărtăşirea de cunoştinţe (Paroutis & Al Saleh, 2009; Teo et al., 2011). În cele din urmă, Kase et al. (2009) sugerează că unul dintre beneficiile formării legate de cunoştinţe este că facilitează dezvoltarea unor bune relaţii interpersonale între cei care o întreprind, ceea ce poate încuraja astfel de oameni să împărtăşească cunoştinţe între ei în viitor.";
const para315 = "4. Coaching-ul şi mentoratul";
const para316 = "Tot mai mulţi autori sugerează, de asemenea, că utilizarea coaching-ului şi a mentoratului în organizaţii poate facilita schimbul informal de cunoştinţe (Garvey & Williamson, 2002; Harrison & Kessels, 2004; Kets de Vries, 2005; Karkoulian et al., 2008; Caligiuri, 2014). Ceea ce au în comun coaching-ul şi mentoratul este că amândouă activităţile sunt preocupate de schimbul de cunoştinţe între o persoană relativ experimentată, mentorul sau coach-ul şi cineva mai puţin experimentat, mentoratul (Wilson & Elman, 1990). Cu toate acestea, ele pot fi distinse între ele pe mai multe niveluri. În primul rând, în timp ce mentoratul are de obicei un interval de timp nedeterminat, coaching-ul este de obicei realizat pe o durată stabilită. În al doilea rând, coaching-ul este de obicei mai structurat în modul în care este organizat, de exemplu, având loc la anumite ore regulate, pentru perioade de timp specifice. În cele din urmă, deşi  coaching-ul este de obicei preocupat de dezvoltarea unor competenţe şi cunoştinţe relativ înguste şi specifice, mentoratul este mai puţin specific.";
const para317 = "Cu toate acestea, atât coaching-ul, cât şi mentoratul pot lua mai multe forme. De exemplu, mentoratul se poate face în moduri foarte formalizate sau relativ informale. Pe de altă parte, coaching-ul se poate realiza în mod individual sau în grup. Beneficiile împărtăşirii de cunoştinţe ale mentoratului şi coaching-ului pot fi ilustrate printr-o serie de experimente scurte. În primul rând, Kets de Vries (2005) în cadrul evaluării unei singure activităţi intensive de coaching de grup, a constatat că dezvoltarea încrederii în rândul participanţilor la această activitate a facilitat împărtăşirea de cunoştinţe interpersonale. În al doilea rând, Karkoulian et al. (2008), într-un studiu al mentoratului în bănicile libaneze a constat că mentoratul informal a avut un impact pozitiv asupra comportamentelor de împărtăşire de cunoştinţe. În al treilea rând, Monks et al. (2016) au clasificat mentoratul ca pe un aspect de „oportunităţi de îmbunătăţire a învăţării”, ceea ce s-a dovedit a fi relaţionat pozitiv cu disponibilitatea oamenilor de a se angaja în procese de împărtăşire de cunoştinţe. În cele din urmă, în studiul leadershipului întreprins de Lee et al. (2010), unul dintre modurile în care liderii de echipă au dezvoltat încrederea în interiorul echipei şi schimbul de cunoştinţe a fost printr-un proces de mentorat, care presupunea relaţionarea  membrilor echipei cu experienţă cu cei mai puţin experimentaţi. Astfel, stabilirea şi facilitarea atât a activităţilor de coaching, cât şi de mentorat reprezintă o altă modalitate prin care schimbul de cunoştinţe interpersonal poate fi facilitat de managementul organizaţional.";
const para318 = "5. Recompensă și evaluare a performanței";
const para319 = "Atunci când vorbim despre recompensă, nu există un consens cu privire la modul în care sistemele de recompensare pot fi utilizate cel mai bine pentru a sprijini activitățile de gestionare a cunoștințelor. Unii cercetători sugerează că recompensarea pentru comportamente adecvate legate de cunoștințe și încorporarea atitudinilor și comportamentelor legate de cunoștințe în procesele de evaluare a performanței reprezintă o modalitate importantă de a utiliza practicile HRM pentru a sprijini eforturile organizaționale de gestionare a cunoștințelor (Cabrera & Cabrera 2005, Oltra 2005). Astfel, studiul întreprins de Lin și Lo (2015) care au vizat angajații din domeniul sănătății din Taiwan a constatat că recompensele financiare erau asociate pozitiv de disponibilitatea de a împărtăși cunoștințele deținute. Mai mult, astfel de sisteme de recompensare trebuie să reflecte strategia particulară de gestionare a cunoștințelor adoptată de o organizație și tipul proceselor de cunoaștere asociate acesteia. De exemplu, Hansen și colab. (1999) susțin că, dacă o strategie de codificare este urmată, sistemele de remunerare și recompensare ar trebui să recunoască eforturile angajaților de a codifica propriile cunoștințe și de a căuta cunoștințele celorlalți, în timp ce cu o strategie de personalizare, sistemele de remunerare și recompensare ar trebui să recunoască eforturile de a împărtăși propriile cunoștințe tacite cu ceilalți. Cu toate acestea, această perspectivă este contestată de un număr semnificativ de cercetători care sugerează că pot exista consecințe negative în ceea ce privește legătura directă dintre recompensele financiare individuale și comportamentele de cunoaștere. De exemplu, Osterloh și Frey (2000), pentru a face distincția între formele de motivație extrinseci (în mare parte formele de motivație financiare) și cele intrinseci (motivația legată de beneficiile derivate din desfășurarea activității în sine), concluzionează că recompensele financiare pot inhiba schimbul de cunoștințe tacite.";
const para320 = "În plus, Fahey și colab. (2007) precum și Milne (2007) ajung la o concluzie similară și susțin că legătura directă dintre recompensele individuale și schimbul de cunoștințe poate însemna că oamenii dezvoltă atitudini instrumentale față de astfel de procese, prin care participă la procesele de cunoaștere numai atunci când obțin o formă de recompensare financiară, care poate inhiba schimbul de cunoștințe atunci când astfel de recompense nu sunt disponibile.";
const para321 = "Mai mult, o susținere suplimentară pentru astfel de idei este oferită de Stenius et al (2015), care a constatat că motivația oamenilor de a împărtăși cunoștințe este asociată negativ cu recompensele financiare, în timp ce Ozlati (2015) a constatat că recompensele financiare nu au legătură cu motivația de împărtășire a cunoștințelor.";
const para322 = "O altă serie de dezbateri își îndreaptă atenția spre a identifica dacă recompensele individuale sau de grup oferă cel mai bun mod de a facilita atitudini și comportamente pozitive legate de cunoștințe. Astfel, unele cercetări sugerează că recompensele financiare orientate individual pot juca un rol pozitiv. De exemplu, Horowitz at al., (2003) au efectuat un sondaj care a vizat lucrătorii din domeniul cunoștințelor din Singapore și au constatat că oferirea unui pachet de remunerare extrem de competitiv a fost clasificat ca fiind cel de-al doilea mod din punct de vedere al eficienței care ajută la menținerea lucrătorilor în cadrul companiilor. ";
const para323 = "În plus, Kankanhalli et al., (2005) și Huang et al., (2008) au constatat, de asemenea, că sistemele de recompensare orientate spre individ susțin participarea la activitățile de gestionare a cunoștințelor. ";
const para324 = "Cu toate acestea, în contradicție cu acest lucru, alți cercetători sugerează că recompensele focalizate pe individ pot inhiba schimbul de cunoștințe nu numai prin crearea unei atitudini instrumentale față de schimbul de cunoștințe, ci și prin modul în care aceste mecanisme de recompensare pot submina sentimentul de apartenență în cadrul echipă sau spiritul comunitar (Nayir & Uzunçarsili 2008). De exemplu, în organizația studiată de Lam (2005), utilizarea recompenselor axate pe individ a contribuit în mod important la cultura individualistă existentă, ceea ce însemna că oamenii nu erau dispuși să codifice și să împărtășească cunoștințele cu colegii. Astfel, cercetătorii sugerează că cel mai bun mod de a dezvolta schimbul de cunoștințe axat pe grup este prin realizarea de recompense bazate pe cunoștințe legate de grup, mai degrabă decât pe cele bazate pe individ (Cabrera & Cabrera 2005).";
const para325 = "În cele din urmă, un număr tot mai mare de cercetători sugerează că recompensele non-financiare, cum ar fi recunoașterea, pot juca un rol important în facilitarea și încurajarea comportamentului adecvat al cunoștințelor (O'Dell & Hubert 2011 Teo et al., 2011; Yeo & Marquardt 2015: Razmerita et al.,. 2016). ";

const paragraph3 = {
    title: titlu3,
    paragraphs: [para31, para32, para33, para34, para35, para36, para37, para38, para39, para311, para312, para313, para314, para315, para316, para317, para318, para319, para320,  para321,  para322,  para323,  para324,  para325 ]
}

const titlu4 = "Capitolul 4- Managementul resurselor umane, retenția personalului și managementul cunoștințelor";
const para41 = "Păstrarea angajaților care dețin cunoștințe valoroase ar trebui să fie un element important din cadrul strategiei de management al cunoștințelor din organizații, pentru a-i motiva să participe la activități de cunoaștere. Acest lucru apare deoarece natura tacită a multor cunoștințe organizaționale se referă la faptul că atunci când angajații părăsesc organizația, aceștia își iau cunoștințele cu ei. Aceasta schimbare de personal poate avea ca și efect pierderea cunoștințelor importante pentru organizație. După cum spunea și Byrne: fără loialitate cunoașterea e pierdută. Oricum, paradoxal, chiar dacă mulți scriitori comentează despre importanța reținerii personalului, foarte puține studii de management al cunoștințelor examinează topicul retenției în detaliu. Câteva dintre studiile care se uită la această problemă sunt considerare aici";
const para42 = "Acest lucru ridică întrebarea asupra ce ar trebui să facă managementul organizațional pentru a induce nivele ridicate de angajament și loialitate printre angajați. Dezvoltarea nivelelor ridicate de angajament nu sunt ușor și direct de realizat. Oricum, cercetările empirice sugerează un număr de factori ce țin de controlul managerial și care afectează nivelurile de angajament: încrederea angajatului în management, acordarea trainingurilor și nivelele suportului organizational.";
const para43 = "În general, literatura despre cunoștințele angajaților și despre firme intensive de cunoaștere, sugerează că dezvoltarea loialități cunoștințelor angajaților, este particular problematică. Aceasta se datorează în mare parte condiției pieței muncii, unde abilitățile și cunoștințele despre cunoștințele angajaților sunt de obicei rare, care crează condiții lucrătorilor din domeniul cunoașterii care sunt favorabile mobilității. În relația cu angajații din domeniul cunoașterii, Joo (2010) a găsit într-un studiu pe companiile din Coreea de Sud, faptul că angajamentul organizațional este facilitat de managerii care manifestă un stil de supervizare puternic și suportiv, dar și de organizațiile care dețin o cultură de învățare. Unul dintre cele mai comprehensive studii despre factorii care influențează nivelul angajamentului organizational a fost condus de Giauque et al. (2010), care a studiat angajați din companii mici din Elveția. Studiul lor a descoperit faptul că trei dintre cei mai importanți factori care influențează angajamentul dintre angajați sunt calitatea reputației organizației, măsura în care există justiție procedurală (în termeni de corectitudine în luarea deciziilor, etc.)  și măsura în care organizația oferă suport pentru cei care nu sunt atât de angajați în muncă, cum ar fi ore mai flexibile pentru a putea facilita responsabilitățile colective.";
const para44 = "Yalabik et al., (2017) a derulat un studiu despre impactul diferitelor tipuri de angajament pe care muncitorii le poseda și felul în care acestea pot conduce spre renuntarea la locul de munca. Studiul lor a fost derulat în rândul muncitorilor din UK  care au lucrat pentru o companie globală de outsourcing și pentru o firma de consultanță. Aceștia au descoperit faptul ca angajamentul la nivel de echipa și angajamentul organizațional fost în mod negativ relationat cu intenția lor de a părăsi organizația și în mod pozitiv relationat cu nivelul lor de angajament profesional.Totuși, relația dintre nivelul de angajament al clientului și intenția de a părăsi organizația nu a fost semnificativă. Bazându-se pe aceste date, Yalabik et al., au venit cu câteva sugestii pentru a reduce intenția oamenilor de a renunța la locul de munca și pentru a dezvolta loialitatea față de organizație. În primul rand, pentru a putea dezvolta acest angajament, angajatorii ar trebui sa  proiecteze locuri de munca interesante și provocatoare, oferindu-le angajaților nivele solide de autonomie. De asemenea, ar trebui sa creeze o cultură puternică de colaborare bazată pe echipă. În cele din urmă, pentru a reduce impactul angajamentului profesional asupra intenției oamenilor de a renunța la locul de muncă, angajatorii ar trebui să ofere tipul de oportunități de formare pe care muncitorii și le doresc și pe care le pot obține de la asociațiile de formare profesională.";
const para45 = "Având o rată mare de fluctuație de personal ridica o problemă semnificativă pentru companiile knowledge intensive (Alvesson 2000; Flood et al., 2001; Beaumont și Hunter 2002). În primul rand, aceasta poate fi considerată o problemă potențială, deoarece cunoștințele deținute de către angajați sunt de obicei tacite. Prin urmare, atunci când părăsesc o organizației, își iau cunoștințele cu ei. De exemplu, o sursă cheie de cunoaștere deținută este capitalul social – cunoașterea cheie a indivizilor. Necesitatea angajaților de a lucra îndeaproape cu organizațiile de tip client înseamnă că aceștia dezvoltă adesea relații strânse cu personalul clientului. Astfel, atunci cand acești oameni pleacă, există riscul pentru angajator de a-și pierde clienții. Al doilea motiv important pentru ca ratele scăzute angajament pot construi o problemă pentru faptul că abilitățile de cunoaștere și experiență deținută sunt un element esențial pentru performanța organizațională.";
const para46 = "Alvesson (2000) argumentează faptul că una dintre cele mai bune modalități prin care putem face față problemelor legate de fluctuația de personal este prin a crea un sentiment de loialitate organizațională. Alvesson identifică două forme mari de loialitate și patru stadii de dezvoltare a acestora (vezi tabelul 15.2). Cea mai slabă formă a loialității așa cum argumentează acesta este loialitatea instrumentală, care se manifestă atunci cand un angajat rămâne loial față de cel care l-a angajat atâta vreme cât ei primesc beneficii personale, iar una dintre cele mai eficiente modalități de a dezvolta o astfel de loialitate este prin plată și condițiile de muncă. Cea mai puternică formă a loialității este cea bazată pe identificare, care constă în faptul că angajatul are un puternic sentiment de identitate ca membru al organizației și se identifică cu scopurile și obiectivele organizației. Acest tip de loialitate nu este de obicei dezvoltat prin recompense financiare și este contruit în schimb, prin dezvoltarea unei culturi organizaționale bazate pe sentimentul de comunitate";

const paragraph4 = {
    title: titlu4,
    paragraphs: [para41, para42, para43, para44, para45, para46]
}

const titlu5 = "Capitolul 5- Concluzii (fara intrebari)";
const para51 = "Focusul central al acestui capitol a fost asupra practicilor HRM  care au potențialul de a facilita și de a susține activitățile de management al cunoștințelor în cadrul unei organizații. În linii mari, managementul organizațional poate folosi practicile HRM pentru a facilita inițiativei de gestionare a cunoștințelor, tratând problemele și provocările care îi pot face pe angajați să nu-și dorească să participe la activitățile de management al cunoștințelor (vezi capitolul 11). Capitolul a ilustrat, de asemenea, rolul pe care îl pot avea practicile specifice HRM ca sisteme de recompensare, designul muncii, formarea și modelarea atitudinilor și comportamentelor muncitorilor în ceea ce privește inițiativele de cunoaștere. În termeni generali, cu excepția sistemelor de recompensă, unele dovezi sunt contradictorii, iar opinia este împărțită. Totuși, există consens cu privire la faptul că practicile HRM ar trebui să fie utilizate pentru a susține inițiativele de management al cunoștințelor.";

const paragraph5 = {
    title: titlu5,
    paragraphs: [para51]
}

export default [paragraph1 , paragraph2, paragraph3, paragraph4, paragraph5];
