const para1="Problemele sociale și culturale au fost din ce în ce mai recunoscute că joacă un rol fundamental în determinarea faptului dacă lucrătorii vor fi dispuși să participe activ la inițiativele de gestionare a cunoștințelor. În mod inevitabil, acest lucru a determinat organizațiile să utilizeze diferite tipuri de practici manageriale pentru a încuraja angajații să participe la activități și inițiative de gestionare a cunoștințelor. Accentul acestui capitol este asupra modului în care diferitele practici de management a resurselor umane (HRM) pot avea un impact asupra atitudinii angajaților față de activitățile de gestionare a cunoștințelor și asupra participării la acestea.";
const para2="Utilizarea practicilor HRM poate fi văzută încercarea de a crea o atitudine pozitivă a angajaților față de participarea la activități de management a cunoștințelor organizaționale, ci și de a-i antrena pe angajați să fie mai loiali angajatorilor lor. Acest lucru se datorează faptului că, în cazul în care lucrătorii nu sunt fideli organizației de care fac parte, există riscul ca aceste organizații să piardă orice acces la cunoștințele lucrătorilor din cauza prin fluctuația de personal (Eckardt și colab. 2014). Problema pierderii de cunoștințe prin fluctuația personalului este o problemă obișnuită cu care se confruntă firmele care necesită cunoștințe specifice. Astfel, practicile HRM legate de sprijinirea eforturilor organizaționale de gestionare a cunoștințelor ar trebui să fie preocupate atât de dezvoltarea angajamentului și a loialității lucrătorilor, cât și de a convinge lucrătorii să împartă sau să creeze cunoștințe.";
const paragraph1 = {
    title:"Capitolul I- Introducere",
    paragraphs:[para1 , para2],
    test:false,
}


const para21 ="Această secțiune ia în considerare două motive separate pentru care practicile HRM pot contribui la apariția comportamentelor și atitudinilor necesare pentru ca inițiativele de management a cunoștințelor să aibă succes. În primul rând, practicile HRM pot fi utilizate pentru a motiva lucrătorii să participe la activități de gestionare a cunoștințelor prin influențarea tipului de factori socio-culturali care au fost descoperiți să fie cruciali pentru participarea angajaților la activitățile de management a cunoștințelor. Al doilea mod în care practicile HRM pot fi utilizate pentru a susține și facilita activitățile de management al cunoștințelor organizaționale este prin dezvoltarea angajamentului organizațional al angajaților, sugerându-se că angajamentul poate fi o variabilă importantă care mediază relația dintre practicile HRM și activitățile de management al cunoștințelor.";
const para22 ="Disponibilitatea angajaților de a participa la activitățile de gestionare a cunoștințelor organizaționale depinde de percepția angajaților asupra posibilelor efecte pozitive și negative ale acestui lucru. Dacă beneficiile posibile sunt mai mari decât dezavantajele, atunci participarea la activități de management al cunoștințelor va fi mai probabilă. Dacă simt opusul, că consecințele negative le pot depăși pe cele pozitive, sunt mai predispuși să-și „păstreze” cunoștințele și să nu participe la activitățile de gestionare a cunoștințelor. Factorii care determină dacă un angajat își împărtășește cunoștințele sau le păstrează, includ măsura în care aceștia percep dacă interesele lor sunt în conflict cu a angajatorii lor, nivelul de  identificare cu  grupul și a comunității și în ce măsură au încredere în colegii lor. Politicile HRM au potențialul de a juca un rol crucial care influențează modul în care angajații rezolvă astfel de decizii de împărtăși sau a păstra cunoștințe prin motivarea acestora de a participarea la activitățile de gestionare a cunoștințelor. De exemplu, dezvoltarea unor bune relații sociale bazate pe încredere sau dezvoltarea unui puternic sentiment de identitate a echipei ar putea fi realizat prin furnizarea de traininguri care să aducă angajații împreună pentru a învăța colectiv sau prin proiectarea de locuri de muncă care necesită colaborare interpersonală";
const para23 ="Vorbind despre motivație, este necesar să se facă distincția între motivația intrinsecă și extrinsecă. Motivația intrinsecă se referă la plăcerile și sentimentele pozitive pe care oamenii le pot obține din simpla desfășurare a unei sarcini sau activități. Astfel, dacă un inginer software obține plăcerea din procesul de scriere a codului computerului care este eficient, ei sunt motivați intrinsec să desfășoare această activitate. În contrast, motivația extrinsecă se referă la recompensele externe pe care le obțin oamenii din îndeplinirea unei sarcini, cum ar fi banii. Astfel, un inginer software este extrinsec motivat să scrie codul computerului dacă principalul motiv pentru care o face este pentru salariul pe care îl primește. Astfel, practicile HRM pot fi utilizate pentru a proiecta locuri de muncă care sunt intrinsec interesante și provocatoare și care încurajează și îi motivează pe angajați să își folosească și să împărtășească cunoștințele lor. În schimb, practica HRM, cum ar fi sistemele de recompensă, pot fi utilizată pentru a motiva în mod extrinsec lucrătorii să participe la activități de gestionare a cunoștințelor, oferind stimulente financiare pentru aceasta.";
const para24 ="A doua modalitate de a înțelege de ce practicile HRM pot influența pozitiv atitudinile și comportamentele legate de cunoștințele lucrătorului este prin conectarea la conceptul de angajament organizațional. Sentimentul de identitate a oamenilor ca parte a unui grup, echipă sau organizație poate influența în mod semnificativ dorința lor de a participa la activitățile de management a cunoștințelor. În termeni generali, cu atât este mai mare sentimentul de identitate a unei persoane cu o echipă sau grup,  cu atât sunt mai susceptibile de a participa la activități de gestionare a cunoștințelor care implică alți membri ai grupului / echipei sau care sunt percepute ca fiind în beneficiul grupului. Astfel, cu cât angajații se identifică mai mult cu organizația pentru care lucrează, cu atât vor avea mai multe șanse să participe la activități de management al cunoștințelor organizaționale. În acest context, rolul practicilor HRM este, prin urmare, de a ajuta la dezvoltarea nivelurilor angajamentului organizațional al angajaților.";
const para25 ="Angajamentul organizațional= Sentimentul de atașament emoțional pe care îl simt oamenii față de organizațiile pentru care lucrează, care se poate reflecta în alinierea valorilor și obiectivelor individuale și organizaționale.";
const para26 ="Un număr de scriitori sugerează că nivelul de angajament pe care îl simt angajații pentru organizațiile în care lucrează poate afecta atât atitudinile și comportamentele lor de partajare a cunoștințelor, cât și nivelul de loialitate (Byrne 2001, Storey și Quintas 2001, Hislop 2002a; O'Neill și Adya 2007, vezi Ilustrația 15.11). Au existat, de asemenea, o serie de studii empirice care au furnizat dovezi în sprijinul acestor argumente. Astfel, Robertson și O'Malley Hammersley (2000) au constatat că nivelurile de angajament organizațional au afectat memoria și atitudinea angajaților față de procesele de cunoaștere. În al doilea rând, Han și colab. (2010), într-un studiu care a implicat personal care lucrează în opt companii taiwaneze de înaltă tehnologie, a constatat că acest lucru este cazul participării angajaților la procesele de luare a deciziilor organizaționale. Astfel, au descoperit că nivelurile de participare la procesele de luare a deciziilor au fost pozitiv legate de sentimentul de  „stăpânire” psihologică pe care lucrătorii îl simțeau asupra unor astfel de decizii, nivelurile de „stăpânire” psihologică fiind legate pozitiv de nivelurile angajaților atât de angajamentul organizațional, cât și de partajarea cunoștințelor. Camelo-Ordaz și colab. (2017) au constatat că o serie de practici HRM cu implicare ridicată (include practici de recrutare și selecție destinate selectării persoanelor pe baza potrivirii lor cu organizația, sisteme de recompensă și evaluare a reclamei bazate pe echipe, sisteme de recompensă care au încurajat schimbul de cunoștințe și furnizarea de oportunități extinse de formare și dezvoltare) a influențat nivelurile de schimb de cunoștințe ale angajaților în mod indirect, afectându-le nivelurile de angajament organizațional.";

const paragraph2 ={
    title:"De ce practicile HRM sunt importante pentru managementul cunoștințelor?",
    paragraphs:[para21 ,para22 , para23 , para24, para25, para26],
    test:false,
}

export default [paragraph1 , paragraph2];